### ISSUE TITLE
Debian todo list

### ISSUE THREAD

**Issue by philclifford** [natanjunges/deb-get#11]
A little collection of "failures" from the debian 11 marathon.  Would be nice to get fixes for some of these before your branch is merged, but after is also good.  I'll take a look tomorrow but now I need sleep!

Some (e.g. nala/nala-legacy) the test fails but deb-get is working fine 
Most just need filtering out or persuading upstream to build for debian

- [ ] battery-monitor depends on gir1.2-appindicator3-0.1
- [ ] Beersmith -   packaged with zstd compression
- [ ] teamviewer barfs
- [ ] system-monitoring-center misses version - maybe missing existing fix
- [ ] stremio misses dependency :     Depends: libfdk-aac1 (>= 0.1.5) but it is not installable
- [ ] opera-stable hangs : does not respect non-interactive and waits on user input forever asking for permission to add an apt list ... Needs to be skipped from CI testing or tested differently
- [X] openrgb PR #10 submitted
- [ ] nala not supported on pre-sid :  test should maybe try to pass correct non-installation identification 
- [ ] minigalaxy depends on unrar :   and installing unrar-free does not satisfy the dependency
- [ ] docker-desktop depends on docker-ce
- [ ] deborah
- [ ] quickobs
- [ ] Bitwarden purge errors - should possibly be handled better
- [ ] Bitwig dependencies not met

```
    The following packages have unmet dependencies:
     bitwig-studio : Depends: zlib1g:i386 but it is not installable
                     Depends: libx11-xcb1:i386 but it is not installable
                     Depends: libx11-6:i386 but it is not installable
                     Depends: libxau6:i386 but it is not installable
                     Depends: libxdmcp6:i386 but it is not installable
                     Depends: libxrender1:i386 but it is not installable
                     Depends: libfontconfig1:i386 but it is not installable
                     Depends: libxcb-icccm4:i386 but it is not installable
                     Depends: libxcb-util1:i386 but it is not installable
                     Depends: libxcb-shm0:i386 but it is not installable
                     Depends: libxcb-xinput0:i386 but it is not installable
                     Depends: libxkbcommon0:i386 but it is not installable
                     Depends: libxkbcommon-x11-0:i386 but it is not installable
                     Depends: libpixman-1-0:i386 but it is not installable
                     Depends: libcairo2:i386 but it is not installable
```

**Comment by natanjunges** [comment]
PR #523 has been merged. Please resubmit to main repo.
